### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by Uwland** [iabsis/igestis#11]
I'm unable to authenticate on Ldap, I got the error:

array(4) {
["type"]=>
int(1)
["message"]=>
string(957) "Uncaught exception 'Doctrine\ORM\ORMException' with message 'The EntityManager is closed.' in /usr/share/igestis/includes/Doctrine/Doctrine/ORM/ORMException.php:78
Stack trace:
#0 /usr/share/igestis/includes/Doctrine/Doctrine/ORM/EntityManager.php(668): Doctrine\ORM\ORMException::entityManagerClosed()
#1 /usr/share/igestis/includes/Doctrine/Doctrine/ORM/EntityManager.php(494): Doctrine\ORM\EntityManager->errorIfClosed()
#2 /usr/share/igestis/includes/coreClasses/IgestisSecurity.php(177): Doctrine\ORM\EntityManager->persist(Object(CoreContacts))
#3 /usr/share/igestis/includes/coreClasses/IgestisSecurity.php(58): IgestisSecurity->__construct(Object(Application))
#4 /usr/share/igestis/includes/coreClasses/Application.php(130): IgestisSecurity::init(Object(Application))
#5 /usr/share/igestis/includes/coreClasses/Application.php(239): Application->__construct()
#6 /usr/share/igestis/public/index.php(5): Application::getInstance()
#7 {main}

thrown"
["file"]=>
string(66) "/usr/share/igestis/includes/Doctrine/Doctrine/ORM/ORMException.php"
["line"]=>
int(78)
}

Debug info:
Error No 8 - Undefined index: WEB_SUBFOLDER - /usr/share/igestis/config/igestis/ConfigIgestisGlobalVars.php (line 266)

**Comment by juanito003** [comment]
I'm unable to authenticate without LDAP. I just made a fresh install 3.0.10 and after the installation, I am redirected to the Login page. But nowhere I could define my login name and password. Or is there a default admin password?

**Comment by olivierb2** [comment]
Normally the defaut admin password is displayed right after you remove the install folder. Or did you made the installation from Debian package? The default is root / password.

**Comment by juanito003** [comment]
Ok thank you, I must have missed it. I installed igestis manually. Would it be a good idea to add it in the installation guide in the README.md?

**Comment by olivierb2** [comment]
Thanks for the suggestion. I added the information into the README.md.

Regards.

Olivier.
