### ISSUE TITLE
Customer issue

### ISSUE THREAD

**Issue by olivierb2** [iabsis/igestis#6]
When I modify a customer, I got the following error:

    SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`igestis`.`CORE_USERS`, CONSTRAINT `fk_CORE_USERS_CORE_CLIENT_TYPE1` FOREIGN KEY (`client_type_code`) REFERENCES `CORE_CLIENT_TYPE` (`code`) ON DELETE NO ACTION ON UPDATE NO ACTION)

**Comment by gilles-hemmerle** [comment]
Could you please test the last commit and tell if you see any other issue (test everywhere the client type is shown in the interface)

Thank you.
