### ISSUE TITLE
Mysql install with clear iGestis install

### ISSUE THREAD

**Issue by olivierb2** [iabsis/igestis#7]
I get the following error during the igestis installation:

Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.consecutive_wrong_login_attempts' in 'field list'' in /usr/share/igestis/includes/Doctrine/Doctrine/DBAL/Connection.php:633

This issue is probably to a missing SQL during the deployment of the new version.

**Comment by gilles-hemmerle** [comment]
How did you install igestis ? With the deb package or with the normal web install ?

**Comment by olivierb2** [comment]
For some reason, I got this error during the installation from the command prompt. Not sure which command make this error, but probably the php command.php which import the SQL itself as I didn't get the success of Mysql import.

**Comment by gilles-hemmerle** [comment]
I've just commited a fix for this issue. Let me know if it's ok

**Comment by gilles-hemmerle** [comment]
This has been solved
