### ISSUE TITLE
Mysql constraint volation when adding new employee

### ISSUE THREAD

**Issue by olivierb2** [iabsis/igestis#8]
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'consecutive_wrong_login_attempts' cannot be null
#0 /usr/share/igestis/includes/Doctrine/Doctrine/DBAL/Statement.php(131): PDOStatement->execute(NULL)
#1 /usr/share/igestis/includes/Doctrine/Doctrine/ORM/Persisters/BasicEntityPersister.php(239): Doctrine\DBAL\Statement->execute()
#2 /usr/share/igestis/includes/Doctrine/Doctrine/ORM/UnitOfWork.php(896): Doctrine\ORM\Persisters\BasicEntityPersister->executeInserts()
#3 /usr/share/igestis/includes/Doctrine/Doctrine/ORM/UnitOfWork.php(304): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#4 /usr/share/igestis/includes/Doctrine/Doctrine/ORM/EntityManager.php(355): Doctrine\ORM\UnitOfWork->commit(NULL)
#5 /usr/share/igestis/controllers/EmployeesController.php(192): Doctrine\ORM\EntityManager->flush()
#6 /usr/share/igestis/includes/coreClasses/IgestisParseRequest.php(149): EmployeesController->newAction()
#7 /usr/share/igestis/includes/coreClasses/IgestisParseRequest.php(27): IgestisParseRequest->LaunchAction()
#8 /usr/share/igestis/public/index.php(7): IgestisParseRequest->__construct(Object(Application))
#9 {main}

**Comment by gilles-hemmerle** [comment]
Should be fixed now

**Comment by gilles-hemmerle** [comment]
This has been solved
