### ISSUE TITLE
Unable to authenticate with latest igestis version

### ISSUE THREAD

**Issue by olivierb2** [iabsis/igestis#9]
I'm unable to authenticate on Ldap, I got the error:

array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(957) "Uncaught exception 'Doctrine\ORM\ORMException' with message 'The EntityManager is closed.' in /usr/share/igestis/includes/Doctrine/Doctrine/ORM/ORMException.php:78
Stack trace:
#0 /usr/share/igestis/includes/Doctrine/Doctrine/ORM/EntityManager.php(668): Doctrine\ORM\ORMException::entityManagerClosed()
#1 /usr/share/igestis/includes/Doctrine/Doctrine/ORM/EntityManager.php(494): Doctrine\ORM\EntityManager->errorIfClosed()
#2 /usr/share/igestis/includes/coreClasses/IgestisSecurity.php(177): Doctrine\ORM\EntityManager->persist(Object(CoreContacts))
#3 /usr/share/igestis/includes/coreClasses/IgestisSecurity.php(58): IgestisSecurity->__construct(Object(Application))
#4 /usr/share/igestis/includes/coreClasses/Application.php(130): IgestisSecurity::init(Object(Application))
#5 /usr/share/igestis/includes/coreClasses/Application.php(239): Application->__construct()
#6 /usr/share/igestis/public/index.php(5): Application::getInstance()
#7 {main}
  thrown"
  ["file"]=>
  string(66) "/usr/share/igestis/includes/Doctrine/Doctrine/ORM/ORMException.php"
  ["line"]=>
  int(78)
}

**Comment by gilles-hemmerle** [comment]
There is no reproductible issue

**Comment by Uwland** [comment]
I got exactly the same error as the OP during the first login.

Debug info:
Error No 8 - Undefined index: WEB_SUBFOLDER - /usr/share/igestis/config/igestis/ConfigIgestisGlobalVars.php (line 266)
